---
- name: Install Apache
  apt:
    name: apache2

- name: Enable Apache Modules
  apache2_module:
    name: '{{ item }}'
  with_items:
    - actions
    - deflate
    - expires
    - headers
    - mime
    - rewrite
    - ssl

- name: Configure Default Apache Site
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache
